//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace formulario_aprendices
{
    using System;
    using System.Collections.Generic;
    
    public partial class aprendices
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> documento { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public Nullable<int> idTipoDocumento { get; set; }
        public Nullable<int> idCiudad { get; set; }
        public Nullable<int> idGenero { get; set; }
    
        public virtual ciudades ciudades { get; set; }
        public virtual generos generos { get; set; }
        public virtual tiposDocumentos tiposDocumentos { get; set; }
    }
}
