//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace formulario_aprendices
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PracticaDataGridEntities : DbContext
    {
        public PracticaDataGridEntities()
            : base("name=PracticaDataGridEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aprendices> aprendices { get; set; }
        public virtual DbSet<ciudades> ciudades { get; set; }
        public virtual DbSet<generos> generos { get; set; }
        public virtual DbSet<tiposDocumentos> tiposDocumentos { get; set; }
    }
}
